full_name: FedStage DRMAA for PBS Pro
short_name: pbs_drmaa
version: "1.0.1"
copyright: Copyright (C) 2006-2009  FedStage Systems
license: GNU General Public License v. 3
license_note: |
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
author: Łukasz Cieśnik
author_email: Łukasz Cieśnik <lukasz.ciesnik@fedstage.com>
maintainer: FedStage Systems
maintainer_email: FedStage DRMAA for PBS users <drmaa-pbspro-users@lists.fedstage.com>
organization: FedStage Systems
url: http://www.fedstage.com/wiki/FedStage_DRMAA_for_PBS_Pro
# download_url: http://example.com/downloads/lalamido
contact_address: drmaa-pbspro-users@lists.fedstage.com
description: DRMAA implementation for PBS Pro
# long_description: |
#   multi-line description
keywords:
  - DRMAA
  - Distributed Resource Management Application API
  - PBS Pro
  - PBS
  - Torque
  - OpenPBS
  - FedStage Systems
classifiers:
  - "Development Status :: 3 - Alpha"
  - "Intended Audience :: Developers"
  - "License :: OSI Approved :: GNU General Public License (GPL)"
  - "Operating System :: POSIX"
  - "Programming Language :: C"
  - "Topic :: System :: Distributed Computing"

ac_config_srcdir: pbs_drmaa/drmaa.c
subproject_dirs:
  - drmaa_utils

